language: ruby
gemfile:
  - gemfiles/activerecord_5.1.gemfile
  - gemfiles/activerecord_5.2.gemfile
  - gemfiles/activerecord_6.0.gemfile
  - gemfiles/activerecord_6.1.gemfile
services:
  - mysql
cache:
  bundler: true

